import { query } from "@anthropic-ai/claude-agent-sdk";
import { existsSync, readFileSync } from "fs";
import path from "path";
import { findClaudeBinary } from "./find-claude-binary";

// Every content section is humanized — no exceptions
const HUMANIZE_SECTIONS = new Set([
  "introduction", "partie-i", "partie-ii", "conclusion",
  "resume", "dedicaces", "remerciements", "bibliographie",
  "section", // fallback for revise route
]);

// Max words per chunk sent to Claude in a single call
const CHUNK_MAX_WORDS = 1200;

// ─── Load system prompt once at startup ──────────────────────────────────────

const systemPath = path.join(process.cwd(), "src/lib/skills/humanize-system.md");
const SYSTEM_PROMPT = existsSync(systemPath)
  ? readFileSync(systemPath, "utf-8")
  : "Tu es un expert en humanisation de texte académique marocain. Réécris le texte fourni pour qu'il soit indétectable par GPTZero et Turnitin. Retourne UNIQUEMENT le texte final, même structure Markdown.";

// ─── Split markdown text into chunks on ## / ### headings ────────────────────
// Each chunk keeps its heading so the humanizer has full context.
// Small sections that don't start with a heading become their own chunk.

function splitIntoChunks(text: string): string[] {
  // Split on lines that start with ## or ### (keep the delimiter with the chunk)
  const parts = text.split(/(?=\n#{2,3} )/);
  const chunks: string[] = [];
  let buffer = "";

  for (const part of parts) {
    const partWords = part.split(/\s+/).filter(Boolean).length;
    const bufferWords = buffer.split(/\s+/).filter(Boolean).length;

    if (bufferWords + partWords > CHUNK_MAX_WORDS && buffer.trim()) {
      chunks.push(buffer.trim());
      buffer = part;
    } else {
      buffer += part;
    }
  }

  if (buffer.trim()) chunks.push(buffer.trim());
  return chunks.length > 0 ? chunks : [text];
}

// ─── Humanize a single chunk ──────────────────────────────────────────────────

async function humanizeChunk(
  chunk: string,
  sectionType: string,
  claudeBinary: string | null,
): Promise<string> {
  let result = "";

  try {
    for await (const message of query({
      prompt: `Applique les 36 patterns de transformation (incluant les patterns français 30-36 et le BURSTINESS CHECKLIST) sur ce texte académique (section: ${sectionType}). Trois passes obligatoires : draft → self-audit → final. Retourne UNIQUEMENT le texte final humanisé, même structure Markdown, aucune explication :\n\n${chunk}`,
      options: {
        systemPrompt: SYSTEM_PROMPT,
        maxTurns: 2,
        allowedTools: [],
        ...(claudeBinary ? { pathToClaudeCodeExecutable: claudeBinary } : {}),
      },
    })) {
      if (message.type === "assistant") {
        for (const block of message.message.content) {
          if (block.type === "text") result += block.text;
        }
      }
    }
  } catch {
    // Never break the pipeline — return the original chunk on failure
    return chunk;
  }

  return result.trim() || chunk;
}

// ─── Public API ───────────────────────────────────────────────────────────────
// Every word generated by every sub-agent passes through this.
// Large sections are chunked by heading and reassembled — nothing is ever skipped.

export async function runInternalHumanize(
  rawText: string,
  sectionType: string,
): Promise<string> {
  if (!HUMANIZE_SECTIONS.has(sectionType)) return rawText;
  if (!rawText.trim()) return rawText;

  const claudeBinary = findClaudeBinary();
  const wordCount = rawText.split(/\s+/).filter(Boolean).length;

  // Small enough to process in one call
  if (wordCount <= CHUNK_MAX_WORDS) {
    return humanizeChunk(rawText, sectionType, claudeBinary);
  }

  // Large section — split by headings, humanize each chunk, reassemble
  const chunks = splitIntoChunks(rawText);
  const humanizedChunks = await Promise.all(
    chunks.map((chunk) => humanizeChunk(chunk, sectionType, claudeBinary)),
  );

  return humanizedChunks.join("\n\n");
}
