import { Router, type IRouter } from "express";
import healthRouter from "./health";
import generateRouter from "./generate";
import sessionRouter from "./session";
import juryRouter from "./jury";
import figuresRouter from "./figures";
import figuresExtractRouter from "./figures-extract";
import shareRouter from "./share";
import stripeRouter from "./stripe";
import reviseRouter from "./revise";
import chatRouter from "./chat";
import humanizeRouter from "./humanize";
import logoRouter from "./logo";
import sdkTestRouter from "./sdk-test";
import plagiatRouter from "./plagiat";
import converseRouter from "./converse";
import summarizeRouter from "./summarize";
import referralRouter from "./referral";
import planApprovalRouter from "./plan-approval";
import adminRouter from "./admin";
// ─── Section agents (each has explicit system prompt + tools) ─────────────────
import introductionRouter from "./introduction";
import dedicacesRouter from "./dedicaces";
import remerciementsRouter from "./remerciements";
import resumeRouter from "./resume";
import sommaireRouter from "./sommaire";
import partieIRouter from "./partie-i";
import partieIIRouter from "./partie-ii";
import conclusionRouter from "./conclusion";
import bibliographieRouter from "./bibliographie";
import annexesRouter from "./annexes";

const router: IRouter = Router();

router.use(healthRouter);
router.use(generateRouter);
router.use(sessionRouter);
router.use(juryRouter);
router.use(figuresRouter);
router.use(figuresExtractRouter);
router.use(shareRouter);
router.use(stripeRouter);
router.use(reviseRouter);
router.use(chatRouter);
router.use(humanizeRouter);
router.use(logoRouter);
router.use(sdkTestRouter);
router.use(plagiatRouter);
router.use(converseRouter);
router.use(summarizeRouter);
router.use(referralRouter);
router.use(planApprovalRouter);
router.use(adminRouter);
// Section agents
router.use(introductionRouter);
router.use(dedicacesRouter);
router.use(remerciementsRouter);
router.use(resumeRouter);
router.use(sommaireRouter);
router.use(partieIRouter);
router.use(partieIIRouter);
router.use(conclusionRouter);
router.use(bibliographieRouter);
router.use(annexesRouter);

export default router;
