import { Router, type IRouter } from "express";
import healthRouter from "./health";
import generateRouter from "./generate";
import sessionRouter from "./session";
import figuresRouter from "./figures";
import figuresExtractRouter from "./figures-extract";
import shareRouter from "./share";
import stripeRouter from "./stripe";
import reviseRouter from "./revise";
import chatRouter from "./chat";
import humanizeRouter from "./humanize";
import logoRouter from "./logo";
import sdkTestRouter from "./sdk-test";
import plagiatRouter from "./plagiat";
import converseRouter from "./converse";
import summarizeRouter from "./summarize";
import referralRouter from "./referral";
import planApprovalRouter from "./plan-approval";
import adminRouter from "./admin";
import meRouter from "./me";
import agentRouter from "./agent";
import feedbackRouter from "./feedback";

const router: IRouter = Router();

router.use(healthRouter);
router.use(generateRouter);
router.use(sessionRouter);
router.use(figuresRouter);
router.use(figuresExtractRouter);
router.use(shareRouter);
router.use(stripeRouter);
router.use(reviseRouter);
router.use(chatRouter);
router.use(humanizeRouter);
router.use(logoRouter);
router.use(sdkTestRouter);
router.use(plagiatRouter);
router.use(converseRouter);
router.use(summarizeRouter);
router.use(referralRouter);
router.use(planApprovalRouter);
router.use(adminRouter);
router.use(meRouter);
router.use(agentRouter);
router.use(feedbackRouter);

export default router;
